image: maven:3.3.9-jdk-8
stages:
  - build_application
  - build_image

# This stage builds your application
build_application:
  stage: build_application
  script:
    - mvn clean install
  artifacts:
    paths:
      - my-application.jar

build_image:
  image: docker:latest
  services:
    - docker:dind
  stage: build_image
  only:
    - master

  # Remember that even though the JAR file was built in a separate image
  #  Gitlab CI will make it available in this image because I specified it in artifacts
  #
  # All I really need to build the Docker image is the artifact(s) & Dockerfile
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build --no-cache=true -t registry.gitlab.com/me/myapp .
    - docker push registry.gitlab.com/me/myapp
